name: Deploy master to Live

on: workflow_dispatch

jobs:
  deploy:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install
        run: npm install
      
      - name: Build
        run: npm run build

      - name: Pre Deploy
        run: |
          cd dist
          cp index.html 404.html
          git config user.name "Leon Latsch"
          git config user.email "dev.leonlatsch@gmail.com"
          git init
          git add -A
          git commit -m "deploy"
      
      - name: Deploy
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: test
          force: true
