name: Deplooy master to Live

on: workflow_dispatch

jobs:
  deploy:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install
        run: npm install
      
      - name: Build
        run: npm run build

      - name: Pre Deploy
        run: sh ci/create_repo_in_dist.sh
      
      - name: Deploy
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: test
